{% set name = "trodi" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d1ed259ba98c35e282ac490e3287ab3824272052f59843d7cef29f44050d339

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  entry_points:
    - trodi = trodi.cli:average_and_label

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy >=1.16.0
    - xarray >=0.16.1
    - netcdf4 >=1.5.4

test:
  imports:
    - trodi
  requires:
    - pytest
  commands:
    - trodi --help

about:
  home: https://github.com/scottstanie/trodi/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Label interferogram pixels or images as outliers
  dev_url: https://github.com/scottstanie/trodi/

extra:
  recipe-maintainers:
    - scottstanie
